- name: Change the working directory to /tmp before executing the command
  ansible.builtin.shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip "awscliv2.zip"
    ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
  args:
    chdir: /tmp